const { Store } = require('../models');

const storesData = [
  // 8 Bangalore Stores
  {
    code: 'BLR-JAY-01',
    name: 'Jayanagar 4th Block Flagship',
    city: 'Bangalore',
    area: 'Jayanagar',
    tier: 'Tier-1',
    store_type: 'Flagship Experience',
    catchment_income: 'Affluent',
    store_size_sqft: 2400,
    footfall_level: 'High',
    footfall_score: 88.0,
    income_score: 94.0,
    demand_profile: 'Flagship / Premium Heavy',
    flagship_preference: 92.0,
    premium_preference: 88.0,
    midrange_preference: 65.0,
    budget_preference: 25.0,
    keypad_preference: 12.0
  },
  {
    code: 'BLR-IND-02',
    name: 'Indiranagar 100ft Experience Center',
    city: 'Bangalore',
    area: 'Indiranagar',
    tier: 'Tier-1',
    store_type: 'Flagship Experience',
    catchment_income: 'Affluent',
    store_size_sqft: 2600,
    footfall_level: 'Very High',
    footfall_score: 95.0,
    income_score: 96.0,
    demand_profile: 'Flagship / Premium Heavy',
    flagship_preference: 95.0,
    premium_preference: 90.0,
    midrange_preference: 60.0,
    budget_preference: 20.0,
    keypad_preference: 10.0
  },
  {
    code: 'BLR-WHI-03',
    name: 'Whitefield ITPL Forum Store',
    city: 'Bangalore',
    area: 'Whitefield',
    tier: 'Tier-1',
    store_type: 'Mall Store',
    catchment_income: 'Upper-Middle',
    store_size_sqft: 2200,
    footfall_level: 'High',
    footfall_score: 86.0,
    income_score: 88.0,
    demand_profile: 'Premium / Mid-range Tech-Savvy',
    flagship_preference: 78.0,
    premium_preference: 85.0,
    midrange_preference: 85.0,
    budget_preference: 40.0,
    keypad_preference: 15.0
  },
  {
    code: 'BLR-KOR-04',
    name: 'Koramangala 80ft Road Hub',
    city: 'Bangalore',
    area: 'Koramangala',
    tier: 'Tier-1',
    store_type: 'High-Street Retail',
    catchment_income: 'Upper-Middle',
    store_size_sqft: 2100,
    footfall_level: 'High',
    footfall_score: 90.0,
    income_score: 86.0,
    demand_profile: 'Premium / Mid-range Youth',
    flagship_preference: 80.0,
    premium_preference: 88.0,
    midrange_preference: 82.0,
    budget_preference: 35.0,
    keypad_preference: 15.0
  },
  {
    code: 'BLR-MAL-05',
    name: 'Malleshwaram 8th Cross Traditional',
    city: 'Bangalore',
    area: 'Malleshwaram',
    tier: 'Tier-1',
    store_type: 'High-Street Retail',
    catchment_income: 'Middle',
    store_size_sqft: 1800,
    footfall_level: 'Very High',
    footfall_score: 92.0,
    income_score: 74.0,
    demand_profile: 'Mid-range / Premium Balanced',
    flagship_preference: 60.0,
    premium_preference: 75.0,
    midrange_preference: 90.0,
    budget_preference: 55.0,
    keypad_preference: 30.0
  },
  {
    code: 'BLR-HSR-06',
    name: 'HSR Layout 27th Main Retail',
    city: 'Bangalore',
    area: 'HSR Layout',
    tier: 'Tier-1',
    store_type: 'Suburban Hub',
    catchment_income: 'Upper-Middle',
    store_size_sqft: 1900,
    footfall_level: 'Moderate',
    footfall_score: 76.0,
    income_score: 84.0,
    demand_profile: 'Premium / Mid-range',
    flagship_preference: 75.0,
    premium_preference: 80.0,
    midrange_preference: 85.0,
    budget_preference: 45.0,
    keypad_preference: 20.0
  },
  {
    code: 'BLR-RAJ-07',
    name: 'Rajajinagar Dr Rajkumar Road',
    city: 'Bangalore',
    area: 'Rajajinagar',
    tier: 'Tier-1',
    store_type: 'High-Street Retail',
    catchment_income: 'Middle',
    store_size_sqft: 1750,
    footfall_level: 'High',
    footfall_score: 82.0,
    income_score: 70.0,
    demand_profile: 'Mid-range / Budget Popular',
    flagship_preference: 48.0,
    premium_preference: 65.0,
    midrange_preference: 88.0,
    budget_preference: 68.0,
    keypad_preference: 40.0
  },
  {
    code: 'BLR-ELC-08',
    name: 'Electronic City Phase 1 Express',
    city: 'Bangalore',
    area: 'Electronic City',
    tier: 'Tier-1',
    store_type: 'City Center',
    catchment_income: 'Middle',
    store_size_sqft: 1600,
    footfall_level: 'Moderate',
    footfall_score: 72.0,
    income_score: 72.0,
    demand_profile: 'Mid-range / Value Seeker',
    flagship_preference: 52.0,
    premium_preference: 68.0,
    midrange_preference: 85.0,
    budget_preference: 65.0,
    keypad_preference: 35.0
  },

  // 17 Tier-2 / Tier-3 Stores across Karnataka
  {
    code: 'MYS-MYS-09',
    name: 'Mysore Mall of Mysore',
    city: 'Mysore',
    area: 'MG Road',
    tier: 'Tier-2',
    store_type: 'Mall Store',
    catchment_income: 'Upper-Middle',
    store_size_sqft: 2000,
    footfall_level: 'High',
    footfall_score: 80.0,
    income_score: 78.0,
    demand_profile: 'Mid-range / Premium Tier-2',
    flagship_preference: 62.0,
    premium_preference: 75.0,
    midrange_preference: 88.0,
    budget_preference: 50.0,
    keypad_preference: 25.0
  },
  {
    code: 'MYS-SAR-10',
    name: 'Mysore Saraswathipuram',
    city: 'Mysore',
    area: 'Saraswathipuram',
    tier: 'Tier-2',
    store_type: 'City Center',
    catchment_income: 'Middle',
    store_size_sqft: 1500,
    footfall_level: 'Moderate',
    footfall_score: 68.0,
    income_score: 66.0,
    demand_profile: 'Mid-range / Budget',
    flagship_preference: 40.0,
    premium_preference: 58.0,
    midrange_preference: 85.0,
    budget_preference: 75.0,
    keypad_preference: 45.0
  },
  {
    code: 'HUB-GOK-11',
    name: 'Hubli Gokul Road Commercial',
    city: 'Hubli',
    area: 'Gokul Road',
    tier: 'Tier-2',
    store_type: 'High-Street Retail',
    catchment_income: 'Middle',
    store_size_sqft: 1600,
    footfall_level: 'High',
    footfall_score: 78.0,
    income_score: 64.0,
    demand_profile: 'Budget / Mid-range Hub',
    flagship_preference: 35.0,
    premium_preference: 52.0,
    midrange_preference: 82.0,
    budget_preference: 88.0,
    keypad_preference: 55.0
  },
  {
    code: 'HUB-CBT-12',
    name: 'Hubli CBT Old City Bazaar',
    city: 'Hubli',
    area: 'CBT Market',
    tier: 'Tier-2',
    store_type: 'City Center',
    catchment_income: 'Budget-conscious',
    store_size_sqft: 1400,
    footfall_level: 'Very High',
    footfall_score: 88.0,
    income_score: 55.0,
    demand_profile: 'Budget / Keypad Heavy',
    flagship_preference: 20.0,
    premium_preference: 38.0,
    midrange_preference: 70.0,
    budget_preference: 95.0,
    keypad_preference: 75.0
  },
  {
    code: 'MNG-FOR-13',
    name: 'Mangalore Forum Fiza Mall',
    city: 'Mangalore',
    area: 'Pandeshwar',
    tier: 'Tier-2',
    store_type: 'Mall Store',
    catchment_income: 'Upper-Middle',
    store_size_sqft: 1900,
    footfall_level: 'High',
    footfall_score: 82.0,
    income_score: 82.0,
    demand_profile: 'Premium / Mid-range Coastal',
    flagship_preference: 70.0,
    premium_preference: 80.0,
    midrange_preference: 85.0,
    budget_preference: 50.0,
    keypad_preference: 25.0
  },
  {
    code: 'MNG-KSR-14',
    name: 'Mangalore KS Rao Road',
    city: 'Mangalore',
    area: 'Hampankatta',
    tier: 'Tier-2',
    store_type: 'High-Street Retail',
    catchment_income: 'Middle',
    store_size_sqft: 1650,
    footfall_level: 'Moderate',
    footfall_score: 74.0,
    income_score: 75.0,
    demand_profile: 'Mid-range / Premium',
    flagship_preference: 58.0,
    premium_preference: 72.0,
    midrange_preference: 88.0,
    budget_preference: 60.0,
    keypad_preference: 35.0
  },
  {
    code: 'BEL-TIL-15',
    name: 'Belgaum Tilakwadi Central',
    city: 'Belgaum',
    area: 'Tilakwadi',
    tier: 'Tier-2',
    store_type: 'High-Street Retail',
    catchment_income: 'Middle',
    store_size_sqft: 1500,
    footfall_level: 'Moderate',
    footfall_score: 70.0,
    income_score: 65.0,
    demand_profile: 'Mid-range / Budget Border Hub',
    flagship_preference: 38.0,
    premium_preference: 55.0,
    midrange_preference: 85.0,
    budget_preference: 80.0,
    keypad_preference: 50.0
  },
  {
    code: 'BEL-KIR-16',
    name: 'Belgaum Kirloskar Road',
    city: 'Belgaum',
    area: 'Kirloskar Rd',
    tier: 'Tier-2',
    store_type: 'City Center',
    catchment_income: 'Budget-conscious',
    store_size_sqft: 1350,
    footfall_level: 'High',
    footfall_score: 76.0,
    income_score: 58.0,
    demand_profile: 'Budget / Mid-range',
    flagship_preference: 28.0,
    premium_preference: 45.0,
    midrange_preference: 78.0,
    budget_preference: 90.0,
    keypad_preference: 65.0
  },
  {
    code: 'DVG-MAN-17',
    name: 'Davangere Mandipet Trade Center',
    city: 'Davangere',
    area: 'Mandipet',
    tier: 'Tier-3',
    store_type: 'City Center',
    catchment_income: 'Budget-conscious',
    store_size_sqft: 1400,
    footfall_level: 'High',
    footfall_score: 75.0,
    income_score: 52.0,
    demand_profile: 'Budget-Heavy Agritech',
    flagship_preference: 20.0,
    premium_preference: 35.0,
    midrange_preference: 68.0,
    budget_preference: 96.0,
    keypad_preference: 80.0
  },
  {
    code: 'TMK-MGR-18',
    name: 'Tumkur MG Road Junction',
    city: 'Tumkur',
    area: 'MG Road',
    tier: 'Tier-3',
    store_type: 'High-Street Retail',
    catchment_income: 'Middle',
    store_size_sqft: 1450,
    footfall_level: 'High',
    footfall_score: 76.0,
    income_score: 60.0,
    demand_profile: 'Budget / Mid-range Student & Agro',
    flagship_preference: 28.0,
    premium_preference: 48.0,
    midrange_preference: 82.0,
    budget_preference: 92.0,
    keypad_preference: 68.0
  },
  {
    code: 'SHM-NEH-19',
    name: 'Shimoga Nehru Road Mall',
    city: 'Shimoga',
    area: 'Nehru Road',
    tier: 'Tier-3',
    store_type: 'City Center',
    catchment_income: 'Middle',
    store_size_sqft: 1380,
    footfall_level: 'Moderate',
    footfall_score: 68.0,
    income_score: 58.0,
    demand_profile: 'Budget / Mid-range Malnad',
    flagship_preference: 25.0,
    premium_preference: 42.0,
    midrange_preference: 80.0,
    budget_preference: 90.0,
    keypad_preference: 70.0
  },
  {
    code: 'BLY-CAR-20',
    name: 'Bellary Car Street Market',
    city: 'Bellary',
    area: 'Car Street',
    tier: 'Tier-3',
    store_type: 'City Center',
    catchment_income: 'Budget-conscious',
    store_size_sqft: 1300,
    footfall_level: 'High',
    footfall_score: 74.0,
    income_score: 54.0,
    demand_profile: 'Budget / Keypad Mining Hub',
    flagship_preference: 22.0,
    premium_preference: 36.0,
    midrange_preference: 72.0,
    budget_preference: 94.0,
    keypad_preference: 82.0
  },
  {
    code: 'GLB-SUP-21',
    name: 'Gulbarga Super Market',
    city: 'Gulbarga',
    area: 'Super Market',
    tier: 'Tier-3',
    store_type: 'City Center',
    catchment_income: 'Budget-conscious',
    store_size_sqft: 1350,
    footfall_level: 'High',
    footfall_score: 78.0,
    income_score: 50.0,
    demand_profile: 'Budget-Heavy Kalyan Karnataka',
    flagship_preference: 18.0,
    premium_preference: 30.0,
    midrange_preference: 65.0,
    budget_preference: 98.0,
    keypad_preference: 88.0
  },
  {
    code: 'UDP-BUS-22',
    name: 'Udupi City Bus Stand Commercial',
    city: 'Udupi',
    area: 'City Bus Stand',
    tier: 'Tier-3',
    store_type: 'High-Street Retail',
    catchment_income: 'Middle',
    store_size_sqft: 1400,
    footfall_level: 'Moderate',
    footfall_score: 72.0,
    income_score: 70.0,
    demand_profile: 'Mid-range / Budget Coastal',
    flagship_preference: 42.0,
    premium_preference: 60.0,
    midrange_preference: 86.0,
    budget_preference: 78.0,
    keypad_preference: 48.0
  },
  {
    code: 'HSN-BMR-23',
    name: 'Hassan BM Road Plaza',
    city: 'Hassan',
    area: 'BM Road',
    tier: 'Tier-3',
    store_type: 'City Center',
    catchment_income: 'Budget-conscious',
    store_size_sqft: 1250,
    footfall_level: 'Moderate',
    footfall_score: 66.0,
    income_score: 52.0,
    demand_profile: 'Budget / Mid-range Planter',
    flagship_preference: 20.0,
    premium_preference: 35.0,
    midrange_preference: 74.0,
    budget_preference: 94.0,
    keypad_preference: 78.0
  },
  {
    code: 'BJP-GAN-24',
    name: 'Bijapur Gandhi Chowk Center',
    city: 'Bijapur',
    area: 'Gandhi Chowk',
    tier: 'Tier-3',
    store_type: 'City Center',
    catchment_income: 'Budget-conscious',
    store_size_sqft: 1200,
    footfall_level: 'High',
    footfall_score: 75.0,
    income_score: 48.0,
    demand_profile: 'Budget-Heavy Heritage',
    flagship_preference: 15.0,
    premium_preference: 28.0,
    midrange_preference: 62.0,
    budget_preference: 98.0,
    keypad_preference: 92.0
  },
  {
    code: 'BDR-MKT-25',
    name: 'Bidar Main Market Plaza',
    city: 'Bidar',
    area: 'Main Market',
    tier: 'Tier-3',
    store_type: 'City Center',
    catchment_income: 'Budget-conscious',
    store_size_sqft: 1150,
    footfall_level: 'Moderate',
    footfall_score: 65.0,
    income_score: 45.0,
    demand_profile: 'Budget / Keypad Northern Gateway',
    flagship_preference: 12.0,
    premium_preference: 24.0,
    midrange_preference: 58.0,
    budget_preference: 98.0,
    keypad_preference: 95.0
  }
];

const seedStores = async () => {
  console.log('[Seed] Seeding 25 Stores across Karnataka...');
  await Store.bulkCreate(storesData, { updateOnDuplicate: Object.keys(storesData[0]) });
  console.log(`[Seed] Successfully seeded ${storesData.length} stores.`);
  return await Store.findAll();
};

module.exports = { seedStores, storesData };
